data_root_dir: /users/zzhan513/data/zzhan513/visual_reasoning/lama/rotational_arc
out_root_dir: /users/zzhan513/data/zzhan513/visual_reasoning/lama/rotational_ARC_results/
tb_dir: /users/zzhan513/data/zzhan513/visual_reasoning/lama/hori_tb_logs/