data_root_dir: /users/zzhan513/data/zzhan513/visual_reasoning/train_lama/lama/horizontal_arc
out_root_dir: /users/zzhan513/data/zzhan513/visual_reasoning/train_lama/lama/horizontal_ARC_results/
tb_dir: /users/zzhan513/data/zzhan513/visual_reasoning/train_lama/lama/hori_tb_logs/