data_root_dir: /users/zzhan513/data/zzhan513/visual_reasoning/lama/mnist_addition
out_root_dir: /users/zzhan513/data/zzhan513/visual_reasoning/lama/mnist_addition_results/
tb_dir: /users/zzhan513/data/zzhan513/visual_reasoning/lama/hori_tb_logs/