data_root_dir: /users/zzhan513/data/zzhan513/visual_reasoning/train_lama/lama/mnist_addition
out_root_dir: /users/zzhan513/data/zzhan513/visual_reasoning/train_lama/lama/ppo_mnist_addition_results/
tb_dir: /users/zzhan513/data/zzhan513/visual_reasoning/train_lama/lama/hori_tb_logs/